[colors.primary]
background = "#14111A"
foreground = "#D8D0DC"

[colors.cursor]
text = "#14111A"
cursor = "#D8D0DC"

[colors.vi_mode_cursor]
text = "#14111A"
cursor = "#D8D0DC"

[colors.search.matches]
foreground = "#14111A"
background = "#D8D0DC"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6B5E72"
background = "#D8D0DC"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#14111A"
red = "#8D5F74"
green = "#6F7B8F"
yellow = "#9A84A2"
blue = "#A87692"
magenta = "#947598"
cyan = "#7E95C1"
white = "#E7DFE9"

[colors.bright]
black = "#6B5E72"
red = "#B57A92"
green = "#8791AE"
yellow = "#BEA2C7"
blue = "#C994B3"
magenta = "#C3A5CA"
cyan = "#94ABD1"
white = "#D8D0DC"

[colors.dim]
black = "#D8D0DC"
red = "#B57A92"
green = "#8791AE"
yellow = "#BEA2C7"
blue = "#C994B3"
magenta = "#C3A5CA"
cyan = "#94ABD1"
white = "#6B5E72"
