# Background and foreground colors
background = #14111A
foreground = #D8D0DC

# Standard colors
palette = 0=#14111A
palette = 1=#8D5F74
palette = 2=#6F7B8F
palette = 3=#9A84A2
palette = 4=#A87692
palette = 5=#947598
palette = 6=#7E95C1
palette = 7=#E7DFE9

# Bright colors
palette = 8=#6B5E72
palette = 9=#B57A92
palette = 10=#8791AE
palette = 11=#BEA2C7
palette = 12=#C994B3
palette = 13=#C3A5CA
palette = 14=#94ABD1
palette = 15=#D8D0DC
