background            #14111A
foreground            #D8D0DC
selection_foreground  #14111A
selection_background  #D8D0DC

cursor                #D8D0DC
cursor_text_color     #14111A

active_tab_foreground   #14111A
active_tab_background   #B6849D
inactive_tab_foreground #B29AAA
inactive_tab_background #14111A
tab_bar_background      #14111A

# black
color0  #14111A
color8  #6B5E72

# red
color1  #8D5F74
color9  #B57A92

# green
color2  #6F7B8F
color10 #8791AE

# yellow
color3  #9A84A2
color11 #BEA2C7

# blue
color4  #A87692
color12 #C994B3

# magenta
color5  #947598
color13 #C3A5CA

#cyan
color6  #7E95C1
color14 #94ABD1

#white
color7  #E7DFE9
color15 #D8D0DC

